#!/bin/bash
# Runs on your host, before the container is created.
set -e

mkdir -p "$HOME/.config/devc/.claude"
mkdir -p "$HOME/.config/devc/.copilot"
mkdir -p "$HOME/.config/devc/.pi"
mkdir -p "$HOME/.config/devc/herdr"

# config.toml is bind-mounted into the container as a *file*, and Docker creates a directory
# at the source path when it does not exist — leaving herdr with a dir where it wants a file.
# So it has to exist before creation. Seeded with the setting
# worth having by default; never overwritten, so later edits (host or container) survive.
herdr_config="$HOME/.config/devc/herdr/config.toml"
[ -f "$herdr_config" ] || printf '%s\n' "onboarding = false" > "$herdr_config"

# Your git identity, for the container.
#
# The container's ~/.gitconfig is wiped on every rebuild, so it has no idea who you are.
# Rather than bind your whole host ~/.gitconfig — which would drag in host paths, credential
# helpers and signing config that do not work in a container — copy just your name and email
# into a file of their own.
#
# `git config --file` does the writing rather than `echo`, so a value containing `#`, `;`,
# `"` or `\` is quoted the way git's own parser expects to read it back. The file is written
# even when you have no identity configured, so the mount source always exists.
#
# The *directory* is what gets mounted, not the file, and the file is replaced whole by a rename.
# This runs on every `devc up` of every project, all sharing this one path, and `git config
# --file` itself writes by rename — so a single-file bind mount would be left holding the old,
# deleted inode in every container already running. On a native Linux daemon that inode had
# just been truncated to the comment line, which left those containers with no identity at all.
# A directory mount resolves the name afresh on each read, so a running container sees the new
# file; building it aside and renaming it in means no reader ever sees a half-written one.
identity_dir="$HOME/.config/devc/git-identity"
mkdir -p "$identity_dir"
tmp="$HOME/.config/devc/.git-identity.$$"
printf '%s\n' "# Generated by devc initialize-command.sh — do not edit." > "$tmp"
name="$(git config --get user.name || true)"
email="$(git config --get user.email || true)"
[ -n "$name" ] && git config --file "$tmp" user.name "$name"
[ -n "$email" ] && git config --file "$tmp" user.email "$email"
mv -f "$tmp" "$identity_dir/gitconfig"

# A non-zero exit here aborts container creation, and the tests above leave a failing status
# when you have no git identity set. Having none is a warning, not a reason to fail the build.
exit 0
