services:
  dhc-server:
    container_name: dhc-server
    image: ghcr.io/deephaven/server:${DHC_VERSION:-edge}
    # This env variable can be set in CI when running in Windows to force linux
    # platform instead of Windows.
    platform: ${COMPOSE_PLATFORM}
    pull_policy: always
    ports:
      - 10000:10000
    environment:
      - START_OPTS=-Xmx4g -DAuthHandlers=io.deephaven.auth.AnonymousAuthenticationHandler -Ddeephaven.console.type=python
