# This action orchestrates CI actions that can be run in parallel. This action
# can be listed by any actions that use `workflow_run` as a trigger that depend
# on all orchestrated actions being completed (e.g. pr-comment.yml).
name: 'Orchestrator'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-unit:
    uses: ./.github/workflows/unit.yml

  call-e2e:
    uses: ./.github/workflows/e2e.yml
