# This configuration is loosely based on documentation here:
# https://github.com/stateful/vscode-awesome-ux/blob/main/docs/TestingExtensions.md#run-tests-in-cicd
name: End-to-end Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - name: Run tests
        # XVFB is used to provide virtual display:
        # https://github.com/coactions/setup-xvfb
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test:e2e
      - name: Upload reports
        uses: actions/upload-artifact@v1
        # if: failure()
        with:
          name: logs
          path: e2e/reports
