name: End-to-end Tests
on:
  workflow_call:

jobs:
  e2e-win:
    runs-on: windows-latest

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      - name: Setup WSL
        uses: Vampire/setup-wsl@v5
        with:
          distribution: Ubuntu-24.04
          set-as-default: true
          update: false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node in WSL using nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
          source /root/.nvm/nvm.sh --no-use
          nvm install
          nvm use
          # echo "script-shell=/bin/bash" >> .npmrc

          echo "NVM version: $(nvm --version)"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          # echo ".npmrc: $(cat .npmrc)"

      - name: Install npm Dependencies
        run: |
          source /root/.nvm/nvm.sh
          npm ci

      - name: Switch Docker to Linux Containers
        shell: cmd
        run: |
          "C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchLinuxEngine
          docker info --format "{{.OSType}}"  # Verify 'linux'

      - name: Run Deephaven Server
        shell: cmd
        run: docker compose --project-directory e2e-testing up -d dhc-server

      - name: Run e2e tests
        run: |
          source /root/.nvm/nvm.sh
          npm run test:e2e

      - name: Stop Deephaven Server
        shell: cmd
        run: docker compose --project-directory e2e-testing down

  e2e:
    # TODO: re-enable
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-e2e
      cancel-in-progress: true

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
      - name: Run end-to-end tests
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            "C:/Program Files/Git/bin/bash.exe" -c "npm run test:e2e"
          else
            npm run test:e2e
          fi

      - name: Upload Screenshots as Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots
          path: e2e-testing/.resources/screenshots
          retention-days: 1
      - name: Publish Test Summary Results
        if: ${{ always() }}
        run: |
          npm run report:ctrfsummary
          sed -i 's/<h3>Test Summary<\/h3>/<h3>End-to-end Test Summary<\/h3>/' $GITHUB_STEP_SUMMARY
          npm run report:prcomment
      - name: Save PR Number
        if: ${{ always() }}
        run: echo ${{ github.event.number }} > pr-comment/PR-number.txt
      - name: Upload Summary as Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: pr-comment
          path: pr-comment/
          retention-days: 1
