name: End-to-end Tests
on:
  workflow_call:

jobs:
  e2e-win:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable WSL and Install Ubuntu
        run: |
          wsl --install -d Ubuntu-20.04
          Start-Sleep -Seconds 30
          wsl --set-default Ubuntu-20.04
          wsl -l -v
        shell: powershell

      - name: Install Node.js in WSL
        run: |
          wsl bash -c "sudo apt update && sudo apt install -y curl"
          wsl bash -c "curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -"
          wsl bash -c "sudo apt install -y nodejs"
          wsl bash -c "node --version && npm --version"
        shell: cmd

      - name: Install npm Dependencies in WSL
        run: |
          wsl bash -c "cd /mnt/c/Users/runneradmin/work/$(basename ${{ github.repository }}) && npm ci"
        shell: cmd

      - name: Run npm Clean Script in WSL
        run: |
          wsl bash -c "cd /mnt/c/Users/runneradmin/work/$(basename ${{ github.repository }}) && npm run test:e2e"
        shell: cmd

  e2e:
    # TODO: re-enable
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-e2e
      cancel-in-progress: true

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
      - name: Run end-to-end tests
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            "C:/Program Files/Git/bin/bash.exe" -c "npm run test:e2e"
          else
            npm run test:e2e
          fi

      - name: Upload Screenshots as Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots
          path: e2e-testing/.resources/screenshots
          retention-days: 1
      - name: Publish Test Summary Results
        if: ${{ always() }}
        run: |
          npm run report:ctrfsummary
          sed -i 's/<h3>Test Summary<\/h3>/<h3>End-to-end Test Summary<\/h3>/' $GITHUB_STEP_SUMMARY
          npm run report:prcomment
      - name: Save PR Number
        if: ${{ always() }}
        run: echo ${{ github.event.number }} > pr-comment/PR-number.txt
      - name: Upload Summary as Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: pr-comment
          path: pr-comment/
          retention-days: 1
