# This configuration is loosely based on documentation here:
# https://github.com/stateful/vscode-awesome-ux/blob/main/docs/TestingExtensions.md#run-tests-in-cicd
name: End-to-end Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - name: Run tests
        run: xvfb-run run test:e2e
        # # XVFB is used to provide virtual display:
        # # https://github.com/coactions/setup-xvfb
        # uses: coactions/setup-xvfb@v1
        # with:
        #   run: npm run test:e2e
      - name: Merge reports
        run: npx ctrf merge e2e/reports --output ctrf-report.json
      - name: Publish Test Summary Results
        # There doesn't seem to be a way to configure the number of retention
        # days here, but we can configure it in the repository settings.
        run: npm run gh:ctrf -- e2e/reports/ctrf-report.json
