name: Unit Tests
on:
  workflow_call:

jobs:
  unit:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-unit
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - name: Run ts checks, linting, and unit tests
        run: npm run test:ci
      - name: Publish Test Summary Results
        if: ${{ always() }}
        run: |
          set -e
          npm run report:junit2ctrf
          npm run report:ctrfsummary
          sed -i 's/<h3>Test Summary<\/h3>/<h3>Unit Test Summary<\/h3>/' $GITHUB_STEP_SUMMARY
          npm run report:prcomment
      - name: Save PR Number
        if: ${{ always() }}
        run: echo ${{ github.event.number }} > pr-comment/PR-number.txt
      - name: Upload Summary as Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: pr-comment-unit
          path: pr-comment/
          retention-days: 1
